import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Loader, FormField } from "../index.js";

export default function CreatePost() {
  const [formData, setFormData] = useState({});
  const [imageLoading, setImageLoading] = useState(false);
  const [sharing, setSharing] = useState(false);
  const navigate = useNavigate();

  const createImage = async () => {
    if (formData.prompt) {
      try {
        setImageLoading(true);
        const response = await fetch("http://localhost:8080/api/v1/dalle", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt: formData.prompt }),
        });
        const data = await response.json();
        setFormData({ ...formData, photo: await data.image });
      } catch (err) {
        console.log(err.data);
      } finally {
        setImageLoading(false);
      }
    }
  };

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const postImage = async () => {
    try {
      setSharing(true);
      const data = await fetch("http://localhost:8080/api/v1/post", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          photo: formData.photo,
          prompt: formData.prompt,
          name: formData.name,
        }),
      });
      await data.json();
      navigate("/");
    } catch (err) {
      console.log(err);
    } finally {
      setSharing(false);
    }
  };

  return (
    <div className="create-post px-5 py-4">
      <div>
        <h1>Create an image.</h1>
        <p className="text text-muted mt-3">
          Create imaginative and visually stunning images generated by DALL-E
          AI, and share them with the community.
        </p>
      </div>
      <form className="d-flex flex-column" action="">
        <FormField
          name={"name"}
          label={"Your name"}
          placeholder={"Jhonn"}
          value={formData.name}
          handleChange={handleChange}
        />
        <FormField
          name={"prompt"}
          label={"Prompt"}
          placeholder={"A dragon fishing in a lake"}
          value={formData.prompt}
          handleChange={handleChange}
        />
        <div className="img-container">
          <img
            src={formData.photo || "src/assets/image-placeholder.webp"}
            className="img-created"
            alt=""
          />
          {imageLoading && (
            <div className="loader-container d-flex align-items-center justify-content-center">
              <Loader />
            </div>
          )}
        </div>

        <button
          type="button"
          onClick={() => createImage()}
          className="my-4 btn btn-primary"
        >
          {imageLoading ? "Generating..." : "Generate"}
        </button>
        <div className="d-flex flex-column flex-md-row align-items-md-center">
          <p className="text-share mt-4">
            Once is ready you can share it with the comunity
          </p>
          <button
            onClick={() => postImage()}
            type="button"
            className="mx-md-5 mt-2 btn btn-success"
          >
            {sharing ? "Sharing..." : "Share Now"}
          </button>
        </div>
      </form>
    </div>
  );
}
