import React, { useEffect, useState } from "react";
import { Loader, FormField } from "../index.js";
import RenderCards from "../components/RenderCards.jsx";
export default function Home() {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([]);
  const [searchText, setSearchText] = useState("");
  const [searchResults, setSearchResults] = useState([]);
  const [searchTimeOut, setSearchTimeOut] = useState(null);

  useEffect(() => {
    fetch("http://localhost:8080/api/v1/post")
      .then((res) => res.json())
      .then((data) => setAllPosts(data.data.reverse()));
  }, []);

  const handleChange = (e) => {
    clearTimeout(searchTimeOut);
    setSearchText(e.target.value);

    setSearchTimeOut(
      setTimeout(() => {
        const results = allPosts.filter((post) =>
          post.prompt.toLowerCase().includes(searchText.toLocaleLowerCase())
        );
        setSearchResults(results);
      }, 700)
    );
  };

  return (
    <div className="py-4 px-5 home">
      <div>
        <h1>The Community Showcase.</h1>
        <p className="text text-muted mt-3">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI.
        </p>
      </div>
      <div className="mt-5 mb-4">
        <FormField
          placeholder={"Search something"}
          value={searchText}
          handleChange={handleChange}
        />
      </div>
      {loading ? (
        <div className="d-flex justify-content-center align-items-center loader-container">
          <Loader />
        </div>
      ) : (
        <div className="results">
          {searchText && (
            <h4 className="text-secondary">
              Showing results for "{searchText}"
            </h4>
          )}
          <div className="result-images row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
            {searchText == "" ? (
              <RenderCards posts={allPosts} />
            ) : (
              <RenderCards posts={searchResults} />
            )}
          </div>
        </div>
      )}
    </div>
  );
}
