import React, { useEffect, useState } from "react";
import { Loader, FormField, Card } from "../index.js";
export default function Home() {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");

  useEffect(() => {
    fetch("http://localhost:8080/api/v1/post")
      .then((res) => res.json())
      .then((data) => console.log(data));
  });

  const handleChange = (e) => {
    setSearchText(e.target.value);
  };

  return (
    <div className="py-4 px-5 home">
      <div>
        <h1>The Community Showcase.</h1>
        <p className="text text-muted mt-3">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI.
        </p>
      </div>
      <div className="mt-5 mb-4">
        <FormField
          placeholder={"Search something"}
          value={searchText}
          handleChange={handleChange}
        />
      </div>
      {loading ? (
        <div className="d-flex justify-content-center align-items-center loader-container">
          <Loader />
        </div>
      ) : (
        <div className="results">
          {searchText && (
            <h4 className="text-secondary">
              Showing results for "{searchText}"
            </h4>
          )}
          <div className="result-images row row-cols-1 row-cols-md-2 row-cols-lg-4">
            <div className="col bg-dark p-1">a</div>
            <div className="col bg-light p-1">a</div>
            <div className="col bg-primary p-1">a</div>
            <div className="col bg-success p-1">a</div>
          </div>
        </div>
      )}
    </div>
  );
}
